
services: 

  mysql:
    image: mysql:8.0
    container_name: mysql_prueba
    ports:
      - "3308:3306"

  mi_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3500:80"

